name = "mjacophoto.blog"
license = "MIT"
licenselink = "https://github.com/mirus-ua/hugo-theme-re-terminal/blob/main/LICENSE.md"
description = "a photography showcase by marshall jacobsen"
homepage = "marsjaco.github.io/mjacophoto.blog"
demosite = "marsjaco.github.io/mjacophoto.blog"
tags = [
  "blog",
  "clean",
  "customizable",
  "dark",
  "highlighting",
  "minimal",
  "monotone",
  "multilingual",
  "personal",
  "responsive",
  "simple",
  "technical",
  "retro",
]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.128

[author]
name = "mjaco"
homepage = "marsjaco.github.io/mjacophoto.blog"

[original]
name = "panr"
homepage = "https://radoslawkoziel.pl"
repo = "https://github.com/panr/hugo-theme-terminal"
